### ISSUE TITLE
Intentionally disabled in PvP?

### ISSUE THREAD

**Issue by hhhogera** [attickdoor/MOActionPlugin#10]
PvP and PvE are different skills, so this plugin cannot be used in PvP.
Is this intentionally disabled?

**Comment by johnysandels** [comment]
Yes, it is purposefully disabled.

**Comment by david-rachwalik** [comment]
Can this addon please receive PvP support?  It's successfully replaced most need for mouseover macros in PvE, but I would very much like to use this addon for PvP even moreso.  It feels doubly important for mouseovers in that environment.

**Comment by johnysandels** [comment]
MOAction won't be a part of PvP because it would be an unfair advantage against others.

**Comment by david-rachwalik** [comment]
Thank you for clarifying your reasoning.  I assume you're primarily referring to the Feast, right? (because it's rated?)
I can understand that - I'm still nearing max level in FFXIV and getting a feel for things, so my initial reaction was "PvE/PvP, what's the difference?" but that's my old WoW mentality where both environments were highly competitive.  I often forget FFXIV's PvE is not as competitive (in a good way.)  I was happy to ask because your plugin seems to work flawlessly in PvE, but I can continue to use my mouseover macros for key abilities in PvP.
