### ISSUE TITLE
What are action stacks?

### ISSUE THREAD

**Issue by MarkusWo** [attickdoor/MOActionPlugin#14]
I couldn't find any explanation for this plugin. What are "action stacks"? I do understand the mouseover settings, but those apparently are using the "old configuration". Can someone maybe explain the difference between the two? Thank You

**Comment by Yoduh** [comment]
I do think the plugin author should add a quick tutorial about this in the README.  I just started using this plugin and had to do some ingame testing to figure it out myself, but anyways this is how it works:

The Base Ability is the ability you want to press to perform an action (which might not actually end up being that same ability)
Base Ability will try to perform one of the abilities you add under it in priority from top to bottom **based on the target field**.
For example as WHM I set my Base Ability as Cure, Ability #&#8203;1 as Cure on UI Mouseover , Ability #&#8203;2 as Aero on Field Mouseover, and Ability #&#8203;3 as Stone on Regular Target.  This means if I mouseover anyone on the UI party list that I will cast Cure on them when I press my Cure hotkey.  If I don't have a UI mouseover target but I instead have a Field mouseover (meaning the mouse is on a character model) it'll be as if my Cure hotkey is actually Aero and will cast that instead.  If I don't have a UI OR Field mouseover but I have a regular target (target bar showing) then my Cure hotkey will cast Stone

Big thing to note is that **cooldowns do not affect the priority**.  You can't use this plugin as a way to "cast X if CD is up, otherwise cast Y".  Meaning if Ability 1 is on CD but it's target requirement is currently being met the Base Ability will continue to try and cast Ability 1 instead of going for Ability 2.  Just something to keep in mind when creating an action stack.

**Comment by Yoduh** [comment]
I do think the plugin author should add a quick tutorial about this in the README. I just started using this plugin and had to do some ingame testing to figure it out myself, but anyways this is how it works:

The Base Ability is the ability you want to press to perform an action (which might not actually end up being that same ability)
Base Ability will try to perform one of the abilities you add under it in priority from top to bottom based on the target field.
For example as WHM I set my Base Ability as Cure, Ability #​1 as Cure on UI Mouseover , Ability #​2 as Aero on Field Mouseover, and Ability #​3 as Stone on Regular Target. This means if I mouseover anyone on the UI party list then I will cast Cure on them when I press my Cure hotkey. If I don't have a UI mouseover target but I instead have a Field mouseover (meaning the mouse is on a character model) it'll be as if my Cure hotkey is actually Aero and will cast that instead. If I don't have a UI OR Field mouseover but I have a regular target (target bar showing) then my Cure hotkey will cast Stone. If I have BOTH a regular target and a UI mouseover target, the UI mouseover target is higher priority so I will cast Cure.

Big thing to note is that cooldowns do not affect the priority. You can't use this plugin as a way to "cast X if CD is up, otherwise cast Y". Meaning if Ability 1 is on CD but it's target requirement is currently being met the Base Ability will continue to try and cast Ability 1 (and fail) instead of going for Ability 2. Just something to keep in mind when creating an action stack.

**Comment by kaedys** [comment]
Would be excellent if, either by default or as a secondary button on the Action Stacks config, all of the "old configuration" settings could be loaded as action stacks.  There are several additional abilities I'd like to add in as Action Stacks, but I really don't want to go through adding a stack definition for the dozens of built-in options under the "old configuration".  Unless they already stack and the UI just isn't clear about it.

**Comment by attickdoor** [comment]
https://youtu.be/pm4eCxD90gs

**Comment by kaedys** [comment]
@attickdoor Is there a convenient way to get all of the "old configuration" mouseover actions into the action stack defs?  Or do we need to go through the dozens and dozens of pre-defined mouseover actions and covert them each individually over to action stacks by hand?  That's really the largest obstacle to me using action stacks at the moment, I don't relish the idea of hand-recreating the def for the near-on 100 abilities with a pre-configured mouseover setting under the "old config" setup.

**Comment by kaedys** [comment]
As a potential alternative to some method of batch-adding defs for the ones that used to have pre-defined ones, you could add a checkbox in Action Stacks mode that causes it to _also_ honor any settings checked in "old configuration" mode (with an Action Stack def for that ability overriding the old config, if both are set).  That would avoid the need to recreate the defs, unless different behavior us desired (which would presumably be the minority of cases), while still leaning on Action Stacks for new defs.

**Comment by attickdoor** [comment]
The "old config" is deprecated and going away in October.

**Comment by kaedys** [comment]
Ok.  Is there going to be a method of generating the existing defs?  Or are exiting users just going to have to start from scratch?
