### ISSUE TITLE
Question regarding future functionality. 

### ISSUE THREAD

**Issue by geetarkev** [attickdoor/MOActionPlugin#2]
Would it be possible to have one keybind use two different spells/abilities based on whether my mouse cursor is over the party list or not.

For example: When my my mouse is over a party member and I press keybind 1 it casts cure 2. When my mouse cursor is not on the party list the same keybind casts glare.

**Comment by attickdoor** [comment]
I see what you're after. That's a possibility, but there are two things to be aware of:
1) That's closer to straight cheating.
2) It would be set per-ability instead of per-bind. So you could have a mouseover alternative to any arbitrary ability.
1 is the real concern for me. If used in conjunction with XIVCombo, some jobs could become vastly simplified. Imagine DPS/tanks having their support buttons bound to mouseover on top of their main combo button. It gets pretty dicey with a bit of ingenuity.

**Comment by geetarkev** [comment]
I brought it up because how I'm used to healing in WoW and it feels great compared to some of the clunkiness you get in FFXIV.

**Comment by attickdoor** [comment]
I played around with macros a tiny bit. It looks like XIV's built-in macro system has some interesting logic that's different for damage and healing abilities that are macroed to MO.

For healing abilities:
1) If there is a MO target, attempt to use the MO ability on the potential target. If this fails, use the MO ability on yourself. In other words, if you're MOed on an enemy and you hit the button, you _**WILL**_ use a heal on yourself.
2) Default to the other action.

For damage abilities:
1) If there is a MO target, attempt to use the MO ability on the potential target.
2) Default to the other action.

Knowing how this works, your request seems well within the bounds of the game's existing macro system. I'll get to work on it in the near future.

**Comment by geetarkev** [comment]
Damn dude, you the GOAT. Appreciate your work on these plugins.

**Comment by attickdoor** [comment]
This might actually evolve MOAction into an "ability priority" plugin, separated by support and damage actions. There's no reason to set individual mouseover states if you can define general behavior, because why wouldn't you want all actions to operate the same? It'll probably take a little bit to do, but I think that's a better direction than trying to keep MOAction the way it is right now.

**Comment by geetarkev** [comment]
Yo you really did it! Thanks for all the hard work, very impressive. Just one thing, holy seems to be missing from the available abilities to stack.
