### ISSUE TITLE
Usage in PVP zones

### ISSUE THREAD

**Issue by starvey** [attickdoor/MOActionPlugin#22]
Hello! I've been trying to use this in any pvp zones, and it does not work. It does work in any other zone so I thought maybe it was a bug. If it is intentional so as to not give an advantage over the other teams, that's fine.

The behaviour also occurs in the wolf's den, if that is of any use for development purpose :)

**Comment by attickdoor** [comment]
Absolutely never going to happen. MOAction is not made for the purpose of giving you an advantage over other players in an environment where only a select number of players can benefit.

I'm not giving you an advantage in Feast Rankings, so that you can steal rewards from someone who doesn't use the plugin.
